title: "group_project_file"
author: "Griffin Thurman, Brett Kuefler, and Hunter Weimar"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Credit Data Cleaning}
credit_data <- read.csv("credit.csv")
library(lubridate)
library(tsibble)
library(fpp3)
library(forecast)
library(dplyr)
nrow <- nrow(credit_data)
credit_data$date <- yearmonth(nrow:1)
head(credit_data$date)
credit_data <- tsibble(credit_data, index = date)
#check
autoplot(credit_data)
colnames(credit_data)[1] <- "Credit"
colnames(credit_data)[2] <- "Date"
```


```{r}
#Exponential Smoothing?
fit <- ses(TRAIN$Credit[1:40], h=40, alpha=.5, initial="simple")
summary(fit)
autoplot(fit)
```

Use box cox for NN
```{r}
lambda <- credit_data %>% 
  features(Credit, features = guerrero) %>% 
  pull(lambda_guerrero)
credit_data <- credit_data%>%
  mutate(bc_credit = box_cox(Credit, lambda))
```


Train and Holdout Data
```{r}
TRAIN <- head(credit_data, nrow(credit_data)*0.8)
HOLDOUT <- tail(credit_data, nrow(credit_data)*0.2)
```


Linear Model
```{r}
LinearFit <- TRAIN%>%
  model(TSLM(Credit~trend()))
report(LinearFit)
```

RMSE function
```{r}
rmse <- function(y_pred, y_actual) {
  sqrt(mean((y_pred - y_actual)^2))
}
```


Forecast and Predict Linear Model
```{r}
LinearFit%>%
  forecast(HOLDOUT, h=12)%>%
  autoplot(TRAIN)
bc_pred <- LinearFit %>% 
  forecast(HOLDOUT)
pred <- inv_box_cox(bc_pred$.mean, lambda)
NextYearPred <- pred
#Uncomment to write preds to csv if left uncommented we would have a lot of csv's
#LogicalPredictions <- write_csv(NextYearPred, "LogicalPredictions.csv")
rmse <- function(y_pred, y_actual) {
  sqrt(mean((y_pred - y_actual)^2))
}
```


Model NN
```{r}
fit <- TRAIN%>%
  model(NNETAR(Credit))
glance(fit)
gg_tsresiduals(fit)
```

Forecast and Predict NN
```{r}
TMP_TRAIN <- head(credit_data, nrow(credit_data) - 12)
TMP_TRAIN <- tail(TMP_TRAIN, nrow(TMP_TRAIN)*0.25)
TMP_HOLDOUT <- tail(HOLDOUT, 12)

fit%>%
  forecast(TMP_HOLDOUT, times = 50)%>%
  autoplot(TMP_TRAIN)

bc_pred <- fit %>% 
  forecast(HOLDOUT, times = 50)
#pred <- inv_box_cox(bc_pred$.mean, lambda)
NextYearPred <- bc_pred$.mean[1:12]
NextYearPred

plot(HOLDOUT$Date[1:12], NextYearPred[1:12])

#Uncomment to write preds to csv if left uncommented we would have a lot of csv's
#NNpredictions <- write.csv(NextYearPred, "NNPredictionsCorrected.csv")
rmse(NextYearPred[1:12], HOLDOUT$Credit[1:12])
```

```{r}
sum(NextYearPred[1:12])
tail(NextYearPred, 1) / head(credit_data$Credit, 1)
```




ETS Model
```{r}
fit <- TRAIN%>%
  model(ETS(bc_credit))

report(fit)
```


Predict and Forecast
```{r}
fit%>%
  forecast(HOLDOUT)%>%
  autoplot(TRAIN)
bc_pred <- fit %>% 
  forecast(HOLDOUT, times = 12)
pred <- inv_box_cox(bc_pred$.mean, lambda)
NextYearPred <- pred

rmse(NextYearPred[1:12], HOLDOUT$Credit[1:12])
```



ARIMA Model
```{r}
fit <- TRAIN%>%
  model(ARIMA(bc_credit~trend()))

report(fit)
gg_tsresiduals(fit)
```

ARIMA Forecast and Predictions
```{r}
fit%>%
  forecast(credit_data, h=12)%>%
  autoplot(TRAIN)

bc_pred <- fit%>%
  forecast(HOLDOUT)

pred <- inv_box_cox(bc_pred$.mean, lambda)
NextYearPred <- pred[1:12]

rmse(NextYearPred, HOLDOUT$Credit[1:12])

#write.csv(NextYearPred, "ARIMA_Predictions.csv")
```

